package de.smahoo.homeos.location;

public enum LocationType {
	LT_NOT_GIVEN,
	LT_OTHER,
	LT_ROOM_LIVING,
	LT_ROOM_KITCHEN,
	LT_ROOM_BATH,
	LT_ROOM_CHILD,
	LT_ROOM_SLEEPING,
	LT_ROOM_STORAGE,
	LT_ROOM_BASEMENT,
	LT_ROOM_CORRIDOR,
	LT_ROOM_OFFICE,
	
	LT_AREA_DEFAULT_OUTSIDE,
	LT_AREA_GARDEN,
	LT_AREA_BALCONY,
	LT_AREA_HOUSE,
	LT_AREA_YARD, 
	LT_AREA_STREET;
	
}
